### ISSUE TITLE
Build system trouble

### ISSUE THREAD

**Issue by pnutus** [Liffon/otp#4]
I had some trouble with the build system. Kept saying `'otp' is up to date`, even though I changed stuff in `types.h`. Had to do a `make clean` to get it back to building.

I don't really know how makefiles work. Do we need to tell it about `types.h`, mayhaps?

**Comment by Liffon** [comment]
Yea, that's probably exactly it. I didn't update the makefile after refactoring.

**Comment by Liffon** [comment]
It should be fixed now.
